print("Jak masz na imie?")
imie = input()
print("Czesc", imie, "milo Cie poznac")
print("Ile zrobiles pompek?")
pompki = input()
print("Wow az", pompki, "Pompek? Jestem dumny z ciebie!")
print("Ile ci to zajelo?")
czas = input()
print("Robiac", pompki, "pompek na", czas, "bedziesz koksem", imie, "!")